# frozen_string_literal: true

require 'rails/generators'

module QuasarScaffold
  module Generators
    class InstallGenerator < Rails::Generators::Base
      source_root File.expand_path('templates', __dir__)

      desc 'Installs QuasarScaffold into a Rails application'

      def create_initializer
        template 'initializer.rb.tt', 'config/initializers/quasar_scaffold.rb'
      end

      def create_frontend_path_stub
        create_file '.quasar_scaffold_frontend_path', ''
        append_to_file '.gitignore', "\n# QuasarScaffold gem frontend path (regenerated by rake task)\n.quasar_scaffold_frontend_path\n"
      end

      def show_post_install_instructions
        say "\n", :green
        say '=' * 70, :green
        say 'QuasarScaffold installed!', :green
        say '=' * 70, :green
        say "\n"
        say 'Next steps:', :yellow
        say "\n"
        say '1. Edit config/initializers/quasar_scaffold.rb to configure your resources', :cyan
        say "\n"
        say '2. Add to config/routes.rb inside your API namespace:', :cyan
        say '     namespace :v1 do'
        say '       quasar_scaffold_resources'
        say '       # ... your other routes'
        say '     end'
        say "\n"
        say '3. Add to frontend/quasar.config.js (inside the build: {} block):', :cyan
        say '     extendViteConf(viteConf) {'
        say '       const fs = require(\'fs\')'
        say '       const path = require(\'path\')'
        say '       const gemPath = fs.readFileSync('
        say '         path.resolve(__dirname, \'../.quasar_scaffold_frontend_path\'),'
        say '         \'utf8\''
        say '       ).trim()'
        say '       viteConf.resolve = viteConf.resolve || {}'
        say '       viteConf.resolve.alias = {'
        say '         ...(viteConf.resolve.alias || {}),'
        say '         \'quasar-scaffold\': gemPath,'
        say '         \'quasar-scaffold-host\': path.resolve(__dirname, \'src\'),'
        say '       }'
        say '     },'
        say "\n"
        say '4. Add to bin/setup (so the frontend path is regenerated after bundle install):', :cyan
        say '     bundle exec rails quasar_scaffold:write_frontend_path'
        say "\n"
        say '5. Run the frontend path task now:', :cyan
        say '     bundle exec rails quasar_scaffold:write_frontend_path'
        say "\n"
      end
    end
  end
end
